# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Login to docker
      run: docker login -u {{secrets.docker_username}} -p {{secrets.docker_password}}
    - name: Build with Maven and push to docker
      working-directory: ./animetracker
      run: mvn clean package -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
