# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven and push to docker
      working-directory: ./animetracker
      run: mvn clean package -Dquarkus.container-image.build=true
    - name: Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: str1xhyper/animetracker
        registry: docker.io
        dockerfile: Dockerfile.native
        directory: ./animetracker/src/main/docker
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

